name: spatial-bc
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - scanpy
    - squidpy
    - anndata
    - cell2location
    - torch
    - torch-geometric
    - scikit-learn
    - pandas
    - numpy
    - matplotlib
    - seaborn
    - tqdm
